sudo: required
dist: trusty

language: node_js
node_js: 10

cache:
  yarn: true
  directories:
    - $HOME/haxe

os:
  - linux

env:
  - HAXE_VERSION=4.0.0-rc.1

install:
  - yarn global add lix && yarn
  - lix install haxe $HAXE_VERSION && lix use haxe $HAXE_VERSION
  - neko -version
  - haxe -version

script:
  - lix run travix interp
  - lix run travix neko
  - lix run travix node
  - lix run travix python
  - lix run travix php
  - lix run travix java
  - lix run travix cs
  - lix run travix lua
  - lix run travix cpp
  # These work but slow down the tests a lot
  #- lix run travix js
  #- lix run travix flash